### ISSUE TITLE
师傅能否再添加一个增加程序信息的功能

### ISSUE THREAD

**Issue by helloyw** [Pizz33/360QVM_bypass#1]
师傅能否再添加一个增加程序信息的功能

**Comment by Pizz33** [comment]
> 师傅能否再添加一个增加程序信息的功能

哈哈如果你仔细看代码你会发现我写了但注释掉 测试了一下随机增加程序信息反而会容易报毒 我研究一下有没别的方法替代

**Comment by helloyw** [comment]
> > 师傅能否再添加一个增加程序信息的功能
> 
> 哈哈如果你仔细看代码你会发现我写了但注释掉 测试了一下随机增加程序信息反而会容易报毒 我研究一下有没别的方法替代

看到了，我想的是ResourceHacker命令行是否能够支持导入资源文件*.res
