### ISSUE TITLE
遇到一个问题

### ISSUE THREAD

**Issue by 4hem** [Pizz33/360QVM_bypass#2]
我在我的计算机上运行这个脚本生成的exe的图标黑乎乎的，不是正确对应的图标
![Snipaste_2023-12-23_18-18-37](https://github.com/Pizz33/360QVM_bypass/assets/44052458/c6ffd563-ae39-4e78-b4e7-d09fcc8ea482)

**Comment by Pizz33** [comment]
> 我在我的计算机上运行这个脚本生成的exe的图标黑乎乎的，不是正确对应的图标
> 
> ![Snipaste_2023-12-23_18-18-37](https://github.com/Pizz33/360QVM_bypass/assets/44052458/c6ffd563-ae39-4e78-b4e7-d09fcc8ea482)
> 
> 
> 
> 

可以试试换个图标 看看行不行🤔
